name: Request Production Deployment

on:
    push:
      branches:
        preview-deploys

jobs:
    request-production-deployment:
        name: Request production deployment
        runs-on: ubuntu-latest

        steps:
          - name: Create new production deployment
            uses: octokit/request-action@v2.x
            env:
                GITHUB_TOKEN: ${{ secrets.EMPLUMS_STAGING_DEPLOYMENT_TOKEN }}
            with:
                route: POST /repos/:owner/:repo/deployments
                mediaType: '{"previews": ["ant-man"]}'
                owner: primer
                repo: components
                ref: 'refs/heads/preview-deploys'
                keep_files: true
                environment: production
                auto_merge: false
                required_contexts: '[]'
                description: Deployment of Primer Components Docs!